### ISSUE TITLE
Adjusting the Cover Image on the "Why Register" Page

### ISSUE THREAD

**Issue by russellelliott** [jcockroft64/sierrahiking#78]
This image features two people using a computer. Specifically, this image:
<img src = "https://i0.wp.com/www.sierrahiking.net/wp-content/uploads/2021/08/annie-spratt-O-40u5howqw-unsplash.jpg?w=2000&ssl=1">

We want it so that the people and the computer are visible, as if they are registering. However, as it is right now, only the top portion of the image is visible.

Here is the custom code I used:
```
<!--CSS for adjusting image position in "Why Register" page-->
<style>
	/*doing top -400px causes the image to disappear */
	@media only screen and (min-width: 767px) {
		.single-featured-image-header{
			top:-400px;
		}
	}
</style>
```

Things we noticed
- doing top as -400px causes the image to disappear on cellphones. that's why I added the media rule to only apply the margin to devices larger than that
- the image isn't aligned right on ultra-wide monitors; the top of the image is shown when we want the center of it to be shown

I think the solution would have the top positioning be a dynamic height. For this, I would have to use Javascript.
- -400px looks good on my MacBook pro which has a screen width of 1792px. Perhaps this can give insight into the calculations required to perfect the image alignment.

This bug also applies to other hiking pages where images' heights would require adjustment to be displayed in a preferred manner.

**Comment by russellelliott** [comment]
Update: Used Javascript to dynamically set the height of the cover image in proportion to the screen size.

I liked the image positioning better on my monitor, as it actually shows the computer in the image. So, I used the ratio -400/1366, with -400 being the original top offset of the image, and 1366 being the screen width of my monitor in pixels.

Here is the code I used:
```
<script>
	function coverImage(){
		//get elements by class name
		//https://www.w3schools.com/jsref/met_document_getelementsbyclassname.asp
			var imageHeaders = document.getElementsByClassName('single-featured-image-header');
			if(window.outerWidth > 767){ //do this for stuff larger than phones
				//CSS !important in Javascript
				//https://stackoverflow.com/questions/38454240/using-css-important-with-javascript
				var ratio = -400/1366; //In my opinion, image looks better on my monitor. Is 1366 wide resolution.
				//https://www.w3schools.com/jsref/prop_win_outerwidth.asp
				var screenWidth = window.outerWidth; //get the screen width
				var newHeight = ratio*screenWidth; //new image height
				imageHeaders[0].style.setProperty('top', newHeight + 'px', 'important');
			}
	}
	
	window.addEventListener('load', coverImage);
	
</script>
```

What does it look like on your end? There needs to be adjustments for tablet, either for the new image position, or just not adjusting it there at all.

**Comment by russellelliott** [comment]
Update: the image is now pegged to the top; the top of the image is always in the same while the bottom changes with the screen width. How does it look on your end?

Here is the custom code:
```
<script>
	function coverImage(){
		//get elements by class name
		//https://www.w3schools.com/jsref/met_document_getelementsbyclassname.asp
			var imageHeaders = document.getElementsByClassName('single-featured-image-header');
			if(window.outerWidth > 767){ //do this for stuff larger than phones
				//CSS !important in Javascript
				//https://stackoverflow.com/questions/38454240/using-css-important-with-javascript
				var image = document.getElementsByClassName('wp-post-image')[0];
				var newHeight = -1*image.height*0.39; //set height related to current cover image height. this pegs the top, allowing the bottom to expand/contract
				imageHeaders[0].style.setProperty('top', newHeight + 'px', 'important');
			}
		
		
	}
	
	window.addEventListener('load', coverImage);
	window.addEventListener('resize', coverImage);
	
</script>
```

**Comment by russellelliott** [comment]
Added Cover Image customization tutorial in the "Tutorials" folder.
https://github.com/jcockroft64/sierrahiking/tree/main/Tutorials/Cover%20Image

**Comment by jcockroft64** [comment]
Done
